name: Deploy Workflow
on: [push, workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code
        uses: actions/checkout@v3
        - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
            node-version: '10.19.0'
        - name: Install dependencies
        run: npm ci
        - name: Build Project
        run: npm run build
        - name: deploy
        run: echo "Deploying..."