
name: "Retry action using retry step"
on:
  # This action is called when this is pushed to github
  push:
  # This action can be manually triggered
  workflow_call:
jobs:
    # This name is up to you
  retry-job:
    runs-on: "ubuntu-latest"
    name: My Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print
        run: |
        echo 'Hello'
