name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main    


jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Install PHP
       - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
      -name: Copy .env file
       run: |
            cp .env.ci .env
      -name: Run composer
       run: |
            composer install --no-interaction          

